### ISSUE TITLE
Milestone 4 - To-do

### ISSUE THREAD

**Issue by nichowu** [UBC-MDS/DSCI_532_Group18_Allstars#28]
1. Add "World" as an option in the drop down menu (Zeliha 'descending & ascending buttoms?)
 
2. When user select the region from the drop down menu, world map will be updated showing the selected region only (Zeliha will try (dropdown selection -> callback -> filter the data frame based on the region selected -> assign to a new df -> update world map with df))

3. Create an altair table at bottom right, connecting to the graph, (2 countries?)  showing (TBD. ) in a table (see lecture note 7) (deepak. + William) 

4. Summary and contributor (disclaimer?) (top with a buttom and bottom) (collapse? html.p?) (William)
5. update "github about" (Nicholas)
6. deploy (automation + creating a new branch in the main repo) (Deepak)
7. reflection + documentation of functions (Nicholas)
8. release + submission (Nicholas)
9. Address peer feedback

**Comment by zmerpez** [comment]
I have created PR for the following. 
- Added "Top 20 Countries" option to region
- Added 2 radio selections for showing all countries or selected. 
- Added 2 radio for ascending or descending order of bar-plot
- Updated world map
- Updated bar-plot

**Comment by williamxu7** [comment]
Closing time for to-do list!
