### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by nichowu** [UBC-MDS/DSCI_532_Group18_Allstars#3]
Meeting Notes for Jan 12, 2021 Lab Session #1

**Items addressed:**
1. Self Introduction
2. Create repo
2. Add license in the repo
3. Teamwork contract, Code of Conduct
4. Selected dataset

**PR:** 
Discussed and agreed that we will create a new branch every time for each task assigned. Once completed, we will push it to our own fork, and then do a pull request from our own fork to the main repo. 

We will also assign reviewers when pushing a PR, and any one of the reviewer can merge the PR as they see fit. 

**Dataset chosen:** 
https://www.kaggle.com/mathurinache/world-happiness-report?select=2020.csv

**To-do:**
1. Contribution Guidelines - Nicholas will upload it later 
2. proposal writeup (https://docs.google.com/document/d/1A2-vTrzkiibF8Atw_0BTbK7SqB0rMm61o7UE1GBT8PA/edit)
3. Description of your app
4. Sketch of your app

**Tasks splits:**
proposal:
	Motivation and purpose: William
	description of data: Deepak
	research questions: Nicholas
	usage:Nicholas
sketch: (to be done with PowerPoints)
	Zeliha
	William 

**Next Meeting:** 

Wednesday Jan 13, 2021 (on slack)
Thursday Jan 14 7:00 p.m. (zoom link TBD)

**Comment by nichowu** [comment]
Meeting Notes for Jan 14, 2021 7:00pm

Items Addressed:
Dataset:  decided to merge cost of living index and population by country files with happiness report.
Motivation and purpose - done
Description of data - done. 
Sketch - reviewed and agreed that we will add two dropdown menu for user to select region and country. Also provided other feedback and Zeliha will finalize tonight. 

To-do:
1. Research questions and usage scenarios - Nicholas has provided an idea and discussed with team members. Will finish writing before next meeting. 
2. Description of your app - William will try to finish writing once Zeliha finalize the sketch based on group feedback.
3. Sketch - Zeliha to finalize
4. Dataset - Deepak to merge all three dataset into one which will include happiness report, population and cost of living expenses. 

Next Meeting:
Friday Jan 15, 2021 11:00 a.m.

**Comment by nichowu** [comment]
Meeting Notes for Jan 14, 2021 11:00a.m.

1. Finalized sketch.png
2. Reviewed and edited "Usage and Research" & "Description of the App" 
3. Put together proposal.md and updated readme.md

To-do:
Please check M1 instruction carefully one more time and if you want to make any necessary changes, communicate on Slack. A release will be created and submission to canvas will be at 11:00 p.m. tonight.

**Comment by williamxu7** [comment]
Meeting Notes for Jan 15, 2021 2:30pm

**Items Addressed:**
Milestone to-do list walkthrough and set expectations
Meeting planned

**Action Plans**:
Work on the Dash file

**Comment by zmerpez** [comment]
Meeting Notes for Jan 22, 2021 11:00am

Items Addressed:
Milestone to-do list walkthrough and set expectations
Added available charts to the app.py
Deployed the app

Action Plans:
Work on the reflection file

**Comment by williamxu7** [comment]
Closing meeting minutes before milestone 4 release
