### ISSUE TITLE
Zoom Meeting Links 

### ISSUE THREAD

**Issue by nichowu** [UBC-MDS/DSCI_532_Group18_Allstars#4]
First Zoom Meeting:

Topic: 532 Milestone 1 Zoom Meeting
Time: Jan 14, 2021 07:00 PM Vancouver

Join Zoom Meeting
https://ubc.zoom.us/j/64374355854?pwd=RHk1b0tGbUNwa3NiZG1CYmlJUk42QT09

Meeting ID: 643 7435 5854
Passcode: 870030

**Comment by williamxu7** [comment]
Thanks Nick!

**Comment by nichowu** [comment]
Topic: 532 Second Zoom Meeting  for M1 
Time: Jan 15, 2021 11:00 AM Vancouver

Join Zoom Meeting
https://ubc.zoom.us/j/67356709910?pwd=S3BKMTRDZ3l4RDNYbm9FbmtkK1Jwdz09

Meeting ID: 673 5670 9910
Passcode: 190318

**Comment by nichowu** [comment]
Zoom link for Thursday Evening:

Topic: 532 Thursday Meeting for M2
Time: Jan 21, 2021 07:00 PM Vancouver
Join Zoom Meeting
https://ubc.zoom.us/j/63642890883?pwd=ZVN0cjJmd2R3dVQvNklkYXhlRlJ4Zz09
Meeting ID: 636 4289 0883
Passcode: 900282

**Comment by nichowu** [comment]
Nicholas Wu is inviting you to a scheduled Zoom meeting.

Topic: 532 Meeting Friday Morning 11:00a.m.
Time: Jan 22, 2021 11:00 AM Vancouver

Join Zoom Meeting
https://ubc.zoom.us/j/65928037277?pwd=cm83MkxsM09IV1QwNEhWMWFCNTRMQT09

Meeting ID: 659 2803 7277
Passcode: 243436
