### ISSUE TITLE
Could you use this optimized version of your GIF?

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI_532_Group18_Allstars#40]
Hey @williamxu7 @deepaksidhu @nichowu @zmerpez  ! Would you mind using this optimized version of your gif? The dashboard is having some performance issues and I am thinking it might be related to all the gifs. It is still pretty good quality and 4 MB instead of 22 MB. I also made it quite a lot shorter (20s instead of 55s), so you can keep your original one in this repo if you want, just make sure to put this one ahead of it in alphabetical order (or in the repo root) Sorry for the trouble!

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4560057/107172774-0fafb780-697b-11eb-87e3-f5fef506efc1.gif)

**Comment by williamxu7** [comment]
Hi @joelostblom, yes! I just uploaded this optimized version GIF and replaced the old one. Hopefully it works. Thank you very much for the master dashboard showcase :)

**Comment by deepaksidhu** [comment]
Hi @joelostblom thank you for the feedback. Appreciate you optimizing the GIF. So the previous GIF was impacting the dashboard's performance through the Heroku app? Thanks again.

**Comment by joelostblom** [comment]
Thank you! I noticed performance was a bit slow on chrome after several groups added gifs so I thought this might be. Not 100% that was the case but it seems better now that I sent out a few optimized gifs.
